name: Build Executables

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r choregraphie_editor/requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          cd choregraphie_editor
          # On utilise --onedir pour créer un dossier au lieu d'un seul fichier
          pyinstaller --noconfirm --onedir --windowed --name "EditeurChore" main.py
          
          # On copie les fichiers de config dans le dossier créé par PyInstaller
          # Le dossier généré s'appelle 'dist/EditeurChore'
          cp OptionsMouvements.csv dist/EditeurChore/
          cp dark.qss dist/EditeurChore/
          cp light.qss dist/EditeurChore/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: choregraphie_editor/dist/EditeurChore/