name: Build Executables

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r choregraphie_editor/requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          cd choregraphie_editor
          # On compile en mode --onefile
          pyinstaller --noconfirm --onefile --windowed --name "EditeurChore" main.py
          
          # On copie les fichiers nécessaires dans le dossier dist/
          # Cela fonctionnera sur Windows, Linux et macOS
          cp OptionsMouvements.csv dist/
          cp dark.qss dist/
          cp light.qss dist/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: choregraphie_editor/dist/